title: "Math2001's blog"
baseURL: https://math2001.github.io
languageCode: en-us
metaDataFormat: yaml
preserveTaxonomyNames: true
publishBranch: master

theme: fasty
author:
  math2001: Mathieu Paturel
copyright: Â© Mathieu Paturel 2017
enableEmoji: true
googleAnalytics: "UA-105735012-1"

blackfriday:
  hrefTargetBlank: true

params:
  disableSearch: true # not available yet
  github_username: math2001
  twitter_username: _math2001
  themefolderpath: themes/fasty
  avatar:
    vector: img/math2001.svg
    raster: img/math2001.png
    alt: Math2001's logo
  favicon: img/math2001.png
  social:
    - username: _math2001
      name: twitter
      url: https://twitter.com/_math2001
    - username: math2001
      name: github
      url: https://github.com/math2001
    - username: math2001
      name: stackoverflow
      url: https://stackoverflow.com/users/6164984/math2001
    - username: math2001
      name: dev.to
      url: https://dev.com/math2001
    - username: math2001
      name: youtube
      url: https://www.youtube.com/channel/UCi2O717lLg8ugD5KxAJTwAQ
  description: |
    :computer: My little open sourced home :tada:
  bio: |
    French, lives in Australia, and gives computer instructions so they don't get bored. :smiley:
  githubcommentsrepo: math2001/math2001.github.io


menu:
  main:
    - url: /post/
      name: Posts
      weight: 1
    - url: /project/
      name: Projects
      weight: 5

  home:
    - url: /post/
      name: Posts
      weight: 1
    - url: /project/
      name: Projects
      weight: 5

  footer:
    - name: Tags
      url: /tags
      weight: 1
    - name: Categories
      url: /categories
      weight: 5
